// Generated by: npm run codegen
// Source: .claude/BE/swagger.json
// DO NOT edit manually. Regenerate when briefingVersion or reportVersion bumps.

// ─── Shared ──────────────────────────────────────────────────────────────────

export interface PagedResult<T> {
  items: T[]
  nextCursor: string | null
  totalCount: number | null
}

// ─── Auth ─────────────────────────────────────────────────────────────────────

export interface LoginRequest {
  email: string
  password: string
}

export interface LoginResponse {
  token: string
}

// ─── Briefing ─────────────────────────────────────────────────────────────────

export interface HookSuggestion {
  text: string
  hookScore: number
  explanationByKey: Record<string, string>
}

export interface CaptionVariant {
  text: string
  tone: string
}

export interface AudioSuggestionCard {
  id: string
  title: string
  artistName: string
  externalListenUrl: string | null
  previewImageUrl: string | null
  durationMs: number
  matchScore: number
  explanationByKey: Record<string, string>
}

export interface PostTimeRecommendation {
  suggestedAtUtc: string
  timeZone: string
  audienceOnlineScore: number
  explanationByKey: Record<string, string>
}

export interface ShelfLifePoint {
  dayOffset: number
  retentionRate: number
}

export interface PredictedAudienceSegment {
  label: string
  fraction: number
}

export interface ReelStudioBriefingDto {
  id: string
  reelDraftId: string
  briefingVersion: number
  createdAtUtc: string
  hookSuggestions: HookSuggestion[]
  captionVariants: CaptionVariant[]
  hashtags: string[]
  audioSuggestions: AudioSuggestionCard[]
  postTimeRecommendations: PostTimeRecommendation[]
  shelfLifeTimeline: ShelfLifePoint[]
  predictedAudienceSegments: PredictedAudienceSegment[]
  overallHookScore: number
  explanationByKey: Record<string, string>
}

export interface AnalyzeDraftRequest {
  caption: string
  hashtags: string[]
  audioId?: string
}

// ─── Story Arcs ───────────────────────────────────────────────────────────────

export interface StoryArcMilestone {
  reelCount: number
  label: string
  reached: boolean
}

export interface StoryArcDto {
  id: string
  state: number
  title: string
  description: string
  theme: string
  suggestedAtUtc: string
  acceptedAtUtc: string | null
  completedAtUtc: string | null
  droppedAtUtc: string | null
  milestones: StoryArcMilestone[]
  commissionBoostPercent: number
  maxEffectiveRate: number
  commissionEarnedFormatted: string
}

export interface DropStoryArcRequest {
  reason?: string
}

// ─── Post-Publish Report ──────────────────────────────────────────────────────

export interface TopMoment {
  atMs: number
  retentionRate: number
  label: string
}

export interface CommentTheme {
  theme: string
  count: number
  sentimentScore: number
}

export interface ConvertingSegment {
  startMs: number
  endMs: number
  conversionRate: number
}

export interface NextStep {
  kind: string
  title: string
  description: string
}

export interface AudienceEvolutionPoint {
  weekOffset: number
  newFollowerRate: number
  retainedFollowerRate: number
}

export interface PostPublishReportDto {
  id: string
  reelId: string
  reportVersion: number
  generatedAtUtc: string
  commissionEarnedFormatted: string
  totalViews: number
  conversionRate: number
  avgRetentionRate: number
  topMoments: TopMoment[]
  commentThemes: CommentTheme[]
  convertingSegments: ConvertingSegment[]
  nextSteps: NextStep[]
  audienceEvolution: AudienceEvolutionPoint[]
  explanationByKey: Record<string, string>
}

// ─── Recipes ──────────────────────────────────────────────────────────────────

export interface ReelRecipeStep {
  order: number
  instruction: string
  tipText: string | null
}

export interface ReelRecipeDto {
  id: string
  title: string
  description: string
  category: string
  steps: ReelRecipeStep[]
  estimatedDurationMs: number
  conversionBenchmark: number
}

export interface RecipesTabPayload {
  featured: ReelRecipeDto[]
  recommended: ReelRecipeDto[]
  all: ReelRecipeDto[]
}

export interface ReelRecipeCitationDto {
  id: string
  reelId: string
  recipeId: string
  citedAtUtc: string
}

export interface CiteRecipeRequest {
  recipeId: string
}

// ─── Stitched Reels ───────────────────────────────────────────────────────────

export interface StitchedReelSuggestionDto {
  id: string
  state: number
  reelId: string
  candidateReelId: string | null
  candidateReelThumbnailUrl: string | null
  candidateCreatorDisplayName: string | null
  candidateCreatorAvatarUrl: string | null
  compatibilityScore: number
  issuedAtUtc: string
  acknowledgedAtUtc: string | null
  dismissedAtUtc: string | null
  explanationByKey: Record<string, string>
}

export interface DismissStitchedReelRequest {
  reason?: string
}

// ─── Boost Offers ─────────────────────────────────────────────────────────────

export interface BoostOfferDto {
  id: string
  reelId: string
  state: number
  offeredAtUtc: string
  expiresAtUtc: string
  serverNowUtc: string
  estimatedReach: number
  isFree: boolean
}

// ─── Activity ─────────────────────────────────────────────────────────────────

export interface CreatorActivityEntryDto {
  id: string
  kind: number
  occurredAtUtc: string
  title: string
  body: string | null
  metadata: Record<string, string> | null
}

// ─── Analytics ────────────────────────────────────────────────────────────────

export interface EarningsTrendPoint {
  periodStart: string
  earningsFormatted: string
  commissionRate: number
}

export interface TopReelDto {
  reelId: string
  title: string
  thumbnailUrl: string | null
  views: number
  conversionRate: number
  earningsFormatted: string
}

export interface AudienceDemographic {
  label: string
  fraction: number
}

export interface BestPostingSlot {
  dayOfWeek: number
  hourLocal: number
  audienceScore: number
}

export interface CreatorDashboardDto {
  fromUtc: string
  toUtc: string
  totalEarningsFormatted: string
  totalViews: number
  avgConversionRate: number
  earningsTrend: EarningsTrendPoint[]
  topReels: TopReelDto[]
  hasData: boolean
}

export interface CreatorAnalyticsOverviewDto {
  fromUtc: string
  toUtc: string
  totalEarningsFormatted: string
  totalViews: number
  avgConversionRate: number
  followersGained: number
  hasData: boolean
}

export interface ContentPerformancePoint {
  reelId: string
  publishedAtUtc: string
  views: number
  conversionRate: number
}

export interface CreatorAnalyticsFullReportDto {
  fromUtc: string
  toUtc: string
  earningsTrend: EarningsTrendPoint[]
  contentPerformance: ContentPerformancePoint[]
  audienceDemographics: AudienceDemographic[]
  bestPostingSlots: BestPostingSlot[]
  hasData: boolean
}

export interface ReelAnalyticsDto {
  reelId: string
  fromUtc: string
  toUtc: string
  views: number
  conversionRate: number
  avgRetentionRate: number
  earningsFormatted: string
  retentionCurve: ShelfLifePoint[]
  hasData: boolean
}
