import type { ModerationItemDto } from '@/api/schema'
import { ModerationItemState, ModerationTargetKind, ModerationSource } from '@/lib/enums'

export const MODERATION_SEED: ModerationItemDto[] = [
  {
    id: 'mod-001-aaaa-bbbb-cccc-dddd',
    targetId: 'reel-8821aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Reel,
    source: ModerationSource.UserReport,
    reportReasonCode: 'HATE_OR_HARASSMENT',
    state: ModerationItemState.Open,
    submittedUtc: '2026-07-27T09:15:00Z',
    assignedTo: null,
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
  {
    id: 'mod-002-aaaa-bbbb-cccc-dddd',
    targetId: 'reel-9922aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Reel,
    source: ModerationSource.UserReport,
    reportReasonCode: 'SPAM',
    state: ModerationItemState.InReview,
    submittedUtc: '2026-07-26T14:30:00Z',
    assignedTo: 'admin-001',
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
  {
    id: 'mod-003-aaaa-bbbb-cccc-dddd',
    targetId: 'review-7733aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Review,
    source: ModerationSource.AutomatedScanner,
    reportReasonCode: 'MISLEADING',
    state: ModerationItemState.Open,
    submittedUtc: '2026-07-27T08:00:00Z',
    assignedTo: null,
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
  {
    id: 'mod-004-aaaa-bbbb-cccc-dddd',
    targetId: 'comment-6644aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.ReelComment,
    source: ModerationSource.UserReport,
    reportReasonCode: 'NUDITY_OR_SEXUAL',
    state: ModerationItemState.Decided,
    submittedUtc: '2026-07-25T11:20:00Z',
    assignedTo: 'admin-002',
    decidedUtc: '2026-07-25T16:45:00Z',
    decision: 2,
    decisionNote: 'Content hidden pending review.',
  },
  {
    id: 'mod-005-aaaa-bbbb-cccc-dddd',
    targetId: 'profile-5555aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Profile,
    source: ModerationSource.UserReport,
    reportReasonCode: 'COUNTERFEIT_PRODUCT',
    state: ModerationItemState.Open,
    submittedUtc: '2026-07-27T10:00:00Z',
    assignedTo: null,
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
  {
    id: 'mod-006-aaaa-bbbb-cccc-dddd',
    targetId: 'reel-4466aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Reel,
    source: ModerationSource.AdminSpot,
    reportReasonCode: 'VIOLENCE',
    state: ModerationItemState.InReview,
    submittedUtc: '2026-07-26T09:30:00Z',
    assignedTo: 'admin-001',
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
  {
    id: 'mod-007-aaaa-bbbb-cccc-dddd',
    targetId: 'review-3377aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Review,
    source: ModerationSource.UserReport,
    reportReasonCode: 'OTHER',
    state: ModerationItemState.Decided,
    submittedUtc: '2026-07-24T13:00:00Z',
    assignedTo: 'admin-003',
    decidedUtc: '2026-07-24T17:30:00Z',
    decision: 1,
    decisionNote: 'No action needed — content is within policy.',
  },
  {
    id: 'mod-008-aaaa-bbbb-cccc-dddd',
    targetId: 'profile-2288aaaa-bbbb-cccc-dddd',
    targetKind: ModerationTargetKind.Profile,
    source: ModerationSource.AutomatedScanner,
    reportReasonCode: 'SPAM',
    state: ModerationItemState.Open,
    submittedUtc: '2026-07-27T07:45:00Z',
    assignedTo: null,
    decidedUtc: null,
    decision: null,
    decisionNote: null,
  },
]
